<?php

/**
 * @file
 * Generic function called to get default places autocomplete options.
 */

/**
 * Default options for autocomplete results.
 *
 * @return array
 *   Array of default configurations.
 */
function places_autocomplete_default_options() {
  return [
    'offset' => '',
    'location' => '',
    'radius' => '',
    'language' => '',
    'types' => '',
    'components' => '',
    'minlength' => '',
  ];
}
