<?php

/**
 * Implements hook_menu().
 */
function places_api_autocomplete_menu() {
  $items['places/autocomplete'] = array(
    'title' => 'Places autocomplete',
    'page callback' => 'places_autocomplete',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/services/places'] = array(
    'title' => 'Google Places API',
    'description' => 'Configure Google Places API settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('places_api_autocomplete_admin_settings'),
    'file' => 'places_api_autocomplete.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function places_autocomplete($string = '') {
  $matches = array();
  if ($string) {
    $key = variable_get('places_api_autocomplete_key', NULL);
    $cacheObject = new GooglePlacesAutocompleteCacheDrupal();
    $options = array();
    $placesApi = new GooglePlacesAutocomplete($key, $cacheObject, $options);
    $result = $placesApi->search($string);
    foreach ($result as $place) {
      $matches[$place->description] = check_plain($place->description);
    }
  }

  drupal_json_output($matches);
}

/**
 * Implements hook_field_widget_info().
 */
function places_api_autocomplete_field_widget_info() {
  /**
   * label: The human-readable name of the widget type.
   * description: A short description for the widget type.
   * field types: An array of field types the widget supports.
   * settings: An array whose keys are the names of the settings available for the widget type, and whose values are the default values for those settings.
   * behaviors: (optional) An array describing behaviors of the widget, with the following elements:
   * multiple values: One of the following constants:
   * FIELD_BEHAVIOR_DEFAULT: (default) If the widget allows the input of one single field value (most common case). The widget will be repeated for each value input.
   * FIELD_BEHAVIOR_CUSTOM: If one single copy of the widget can receive several field values. Examples: checkboxes, multiple select, comma-separated textfield.
   * default value: One of the following constants:
   * FIELD_BEHAVIOR_DEFAULT: (default) If the widget accepts default values.
   * FIELD_BEHAVIOR_NONE: if the widget does not support default values.
   * weight: (optional) An integer to determine the weight of this widget relative to other widgets in the Field UI when selecting a widget for a given field instance.
   */

  return array(
    'places_autocomplete' => array(
      'label' => 'Google Places Autocomplete',
      'description' => 'A text field with Google Places API Autocomplete',
      'field types' => array('text'),
      'settings' => array('size' => 60),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function places_api_autocomplete_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  if ($widget['type'] == 'places_autocomplete') {
    $form['size'] = array(
      '#type' => 'textfield',
      '#title' => t('Size of textfield'),
      '#default_value' => $settings['size'],
      '#required' => TRUE,
      '#element_validate' => array('element_validate_integer_positive'),
    );
  }

  return $form;

}

/**
 * Implements hook_field_widget_form().
 */
function places_api_autocomplete_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $element['value'] = array(
    '#type' => 'textfield',
    '#title' => $instance['label'],
    '#default_value' => isset($items[$delta]['value']) ? $items[$delta]['value'] : NULL,
    '#size' => $instance['widget']['settings']['size'],
    '#maxlength' => $field['settings']['max_length'],
    '#attributes' => array('class' => array('text-full')),
    '#autocomplete_path' => 'places/autocomplete',
  );

  return $element;
}
